server/api/urls.py
from django.conf.urls import url
from api.views import home_view
from api.views import users_view, user_view
from api.views import products_view, product_view
from api.views import companies_view, company_view
from api.views import traits_view, trait_view
from api.views import ideologies_view, ideology_view

urlpatterns = [
    url(r'^$', home_view, name='api_home'),
]

urlpatterns += [
    url(r'^users/all/(?P<start>\d+)-(?P<offset>\d+)$', users_view),
    url(r'^users/all/(?P<start>\d+)$', users_view),
    url(r'^users/all/$', users_view),

    url(r'^users/(?P<start>\d+)-(?P<offset>\d+)$', users_view),
    url(r'^users/(?P<pk>\d+)$', user_view),
    url(r'^users/$', users_view)
]

urlpatterns += [
    # url(r'^products/$', )
    url(r'^products/all/(?P<start>\d+)-(?P<offset>\d+)$', products_view),
    url(r'^products/all/(?P<start>\d+)$', products_view),
    url(r'^products/all/$', products_view),

    url(r'^products/(?P<start>\d+)-(?P<offset>\d+)$', products_view),
    url(r'^products/(?P<pk>\d+)$', product_view),
    url(r'^products/$', products_view)
]

urlpatterns += [
    url(r'^companies/all/(?P<start>\d+)-(?P<offset>\d+)$', companies_view),
    url(r'^companies/all/(?P<start>\d+)$', companies_view),
    url(r'^companies/all/$', companies_view),

    url(r'^companies/(?P<start>\d+)-(?P<offset>\d+)$', companies_view),
    url(r'^companies/(?P<pk>\d+)$', company_view),
    url(r'^companies/$', companies_view)
]

urlpatterns += [
    url(r'^traits/all/(?P<start>\d+)-(?P<offset>\d+)$', traits_view),
    url(r'^traits/all/(?P<start>\d+)$', traits_view),
    url(r'^traits/all/$', traits_view),

    url(r'^traits/(?P<start>\d+)-(?P<offset>\d+)$', traits_view),
    url(r'^traits/(?P<pk>\d+)$', trait_view),
    url(r'^traits/$', traits_view)
]

urlpatterns += [
    url(r'^ideologies/all/(?P<start>\d+)-(?P<offset>\d+)$', ideologies_view),
    url(r'^ideologies/all/(?P<start>\d+)$', ideologies_view),
    url(r'^ideologies/all/$', ideologies_view),

    url(r'^ideologies/(?P<start>\d+)-(?P<offset>\d+)$', ideologies_view),
    url(r'^ideologies/(?P<pk>\d+)$', ideology_view),
    url(r'^ideologies/$', ideologies_view)
]

server/company/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'error/(?P<code>\d{3})/$', views.error, name='error'),
    url(r'^search$', views.search, name='search'),
    url(r'^search/$', views.search, name='search'),
    url(r'^details/(?P<comp_id>\d+)/$', views.company_details, name='details'),
]

server/server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from edec_account.views import index, error
from .settings import MEDIA_ROOT
from .views import base_html_view


urlpatterns = [
    # already configured urls
    url(r'^admin/', admin.site.urls),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # custom urls
    url(r'^$', index, name='index'),
    url(r'^index$', index, name='index'),
    url(r'^index.php$', index, name='index'),
    url(r'^index.html$', index, name='index'),
    url(r'^error$', error, name='error'),
    url(r'^error/(?P<code>\d{3})/$', error, name='error'),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^accounts/', include('edec_account.urls')),
    url(r'^products/', include('product.urls', namespace='product')),
    url(r'^companies/', include('company.urls', namespace='company')),

    # test urls
    url(r'^test$', base_html_view, name='test')
]

server/templates/base.html
{% load avatar_tags %}
<!DOCTYPE html>
<html>
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{% block head_title %}EDEC{% endblock %}</title>
        {% load staticfiles %}
        <!-- core CSS -->
        <link href="{% static 'global/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'global/css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'global/css/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'global/css/prettyPhoto.css' %}" rel="stylesheet">
        <link href="{% static 'global/css/main.css' %}" rel="stylesheet">
        <link href="{% static 'global/css/responsive.css' %}" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="{% static 'global/js/html5shiv.js' %}"></script>
        <script src="{% static 'global/js/respond.min.js' %}"></script>
        <![endif]-->
        <link rel="shortcut icon" href="{% static 'global/images/ico/favicon.ico' %}">
        <link rel="apple-touch-icon-precomposed" sizes="144x144"
              href="{% static 'global/images/ico/apple-touch-icon-144-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="114x114"
              href="{% static 'global/images/ico/apple-touch-icon-114-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72"
              href="{% static 'global/images/ico/apple-touch-icon-72-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed"
              href="{% static 'global/css/images/ico/apple-touch-icon-57-precomposed.png' %}">
        {% block extra_head %}
        {% endblock %}
    {% endblock %}
</head>
<body class="homepage">
<header id="header">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
        <div class="no-margin" style="padding-left: 30px;padding-right: 30px">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'global/images/edeclogo.png' %}"
                                                                      alt="logo"></a>
            </div>
            <div class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li{% block home_active %} {% endblock %}><a href="{% url 'index' %}">Home</a></li>
                    <li{% block products_active %} {% endblock %}><a href="{% url 'product:search' %}">Products</a></li>
                    <li{% block company_active %} {% endblock %}><a href="{% url 'company:search' %}">Companies</a></li>
                    {% if not user.is_authenticated %}
                        <li><a href="{% url 'account_login' %}">Login</a></li>
                    {% else %}
                        <li{% block account_active %} {% endblock %}><a href="{% url 'account_profile' %}">My
                            Account</a></li>
                        <li><a href="{% url 'account_logout' %}">Logout</a></li>
                        <li>{% avatar user 45 %}</li>
                    {% endif %}
                </ul>
            </div>
        </div><!--/.container-->
    </nav><!--/nav-->
    {% block extra_header %}

    {% endblock %}
</header><!--/header-->
{% block body %}
    {% block content %}
    {% endblock %}
{% endblock %}
{% block extra_body %}
{% endblock %}
<footer id="footer" class="midnight-blue footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-xs-4">
                &copy; 2016 <a target="_blank" href="http://shapebootstrap.net/" title="EDEC">EDEC</a>
            </div>
            <div class="col-sm-6 col-xs-8">
                <div class="social">
                    <ul class="social-share">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-skype"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div><!--/.container-->
</footer><!--/#footer-->
{% block scripts %}
<script src="{% static 'global/js/jquery.js' %}"></script>
<script src="{% static 'global/js/bootstrap.min.js' %}"></script>
<script src="{% static 'global/js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'global/js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'global/js/main.js' %}"></script>
<script src="{% static 'global/js/wow.min.js' %}"></script>
{% block extra_js %}
{% endblock %}
{% endblock %}
</body>
</html>