server/api/urls.py
from django.conf.urls import url
from api.views import home_view
from api.views import users_view, user_view
from api.views import products_view, product_view
from api.views import companies_view, company_view
from api.views import traits_view, trait_view
from api.views import ideologies_view, ideology_view

urlpatterns = [
    url(r'^$', home_view, name='api_home'),
]

urlpatterns += [
    url(r'^users/all/(?P<start>\d+)-(?P<offset>\d+)$', users_view),
    url(r'^users/all/(?P<start>\d+)$', users_view),
    url(r'^users/all/$', users_view),

    url(r'^users/(?P<start>\d+)-(?P<offset>\d+)$', users_view),
    url(r'^users/(?P<pk>\d+)$', user_view),
    url(r'^users/$', users_view)
]

urlpatterns += [
    # url(r'^products/$', )
    url(r'^products/all/(?P<start>\d+)-(?P<offset>\d+)$', products_view),
    url(r'^products/all/(?P<start>\d+)$', products_view),
    url(r'^products/all/$', products_view),

    url(r'^products/(?P<start>\d+)-(?P<offset>\d+)$', products_view),
    url(r'^products/(?P<pk>\d+)$', product_view),
    url(r'^products/$', products_view)
]

urlpatterns += [
    url(r'^companies/all/(?P<start>\d+)-(?P<offset>\d+)$', companies_view),
    url(r'^companies/all/(?P<start>\d+)$', companies_view),
    url(r'^companies/all/$', companies_view),

    url(r'^companies/(?P<start>\d+)-(?P<offset>\d+)$', companies_view),
    url(r'^companies/(?P<pk>\d+)$', company_view),
    url(r'^companies/$', companies_view)
]

urlpatterns += [
    url(r'^traits/all/(?P<start>\d+)-(?P<offset>\d+)$', traits_view),
    url(r'^traits/all/(?P<start>\d+)$', traits_view),
    url(r'^traits/all/$', traits_view),

    url(r'^traits/(?P<start>\d+)-(?P<offset>\d+)$', traits_view),
    url(r'^traits/(?P<pk>\d+)$', trait_view),
    url(r'^traits/$', traits_view)
]

urlpatterns += [
    url(r'^ideologies/all/(?P<start>\d+)-(?P<offset>\d+)$', ideologies_view),
    url(r'^ideologies/all/(?P<start>\d+)$', ideologies_view),
    url(r'^ideologies/all/$', ideologies_view),

    url(r'^ideologies/(?P<start>\d+)-(?P<offset>\d+)$', ideologies_view),
    url(r'^ideologies/(?P<pk>\d+)$', ideology_view),
    url(r'^ideologies/$', ideologies_view)
]

server/company/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'error/(?P<code>\d{3})/$', views.error, name='error'),
    url(r'^search$', views.search, name='search'),
    url(r'^search/$', views.search, name='search'),
    url(r'^details/(?P<comp_id>\d+)/$', views.company_details, name='details'),
]

server/server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from edec_account.views import index, error
from .settings import MEDIA_ROOT
from .views import base_html_view


urlpatterns = [
    # already configured urls
    url(r'^admin/', admin.site.urls),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # custom urls
    url(r'^$', index, name='index'),
    url(r'^index$', index, name='index'),
    url(r'^index.php$', index, name='index'),
    url(r'^index.html$', index, name='index'),
    url(r'^error$', error, name='error'),
    url(r'^error/(?P<code>\d{3})/$', error, name='error'),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^accounts/', include('edec_account.urls')),
    url(r'^products/', include('product.urls', namespace='product')),
    url(r'^companies/', include('company.urls', namespace='company')),

    # test urls
    url(r'^test$', base_html_view, name='test')
]

server/company/forms.py
__author__ = 'vlupoaie'

from django import forms


class SearchCompany(forms.Form):
    category = forms.CharField(max_length=64)
    query = forms.CharField(max_length=64, required=False)
    order = forms.CharField(max_length=64, initial='Alphabetic Ascending')

    def __init__(self, *args, **kwargs):
        super(SearchCompany, self).__init__(*args, **kwargs)
        # category
        self.fields['category'].widget = forms.HiddenInput()
        self.fields['category'].widget.attrs.update({
            'id': 'hiddenCategoryCompany'
        })
        # query
        self.fields['query'].widget.attrs.update({
            'class': 'form-control'
        })
        # order
        self.fields['order'].widget = forms.HiddenInput()
        self.fields['order'].widget.attrs.update({
            'id': 'hiddenFilterCompany'
        })

server/company/views.py
from django.core.exceptions import *
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponseNotAllowed, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from server.settings import BASE_DIR
from .models import *
from .forms import *
from company.models import Compliance, Approval, Ideology

import re
import operator
from functools import reduce
from PIL import Image
from urllib.parse import urlencode


def error(request, code):
    integer_code = int(code)
    messages = {
        400: "Bad request",
        404: "Page not found",
        405: "Request not allowed",
    }
    extended_messages = {
        400: "Request type or parameters are not allowed !",
        404: "The page you are looking for does not exist !",
        405: "The request you made is not allowed !",
    }
    context = {
        'code': integer_code,
        'message': messages.get(integer_code, 'Unknown error'),
        'extended_message': extended_messages.get(integer_code, 'An unknown error occurred. Please contact a site administrator !')
    }
    return render(request, 'edec_account/error.html', context)


@login_required
def search(request):
    # treat a post request on the search page
    if request.method == 'POST':
        return HttpResponseRedirect('/search')

    # treat a get request on the search page
    last_page = 1
    if request.method == 'GET':
        print(1)
        page_nr = request.GET.get('page', 1)
        try:
            page_nr = int(page_nr)
            if page_nr < 0:
                raise Exception('Page number is negative')
        except Exception as exc:
            print('Exception: {}'.format(exc))
            return HttpResponseRedirect('/error/400/')
        first_slice = (page_nr-1) * 10
        second_slice = page_nr * 10
        flag = False
        print(2)
        if len(request.GET) > 1:
            search_form = SearchCompany(request.GET)
            if search_form.is_valid():
                # rename cleaned data
                query = search_form.cleaned_data
                print(query)
                category = query['category']
                print(3)
                # build word searching queries
                queries = query['query'].split()
                if queries:
                    query_set = reduce(operator.__or__, [Q(name__icontains=query) for query in queries])
                else:
                    query_set = Q(name__icontains='')

                if query['order'] == 'Relevance Descending':
                    objects = Company.objects.get_preference_ordered(request.user.profile.id, first_slice - 1, second_slice,
                                                                     query['query'], query['token_from'],
                                                                     query['token_to'], 'desc')
                elif query['order'] == 'Relevance Ascending':
                    objects = Company.objects.get_preference_ordered(request.user.profile.id, first_slice - 1, second_slice,
                                                                     query['query'], query['token_from'],
                                                                     query['token_to'], 'asc')
                else:
                    # parse order by and form string for order
                    order_by = 'name'
                    if query['order'] == 'Alphabetic Ascending':
                        order_by = 'name'
                    elif query['order'] == 'Alphabetic Descending':
                        order_by = '-name'
                    elif query['order'] == 'Relevance Descending':
                        order_by = 'score'
                    elif query['order'] == 'Relevance Ascending':
                        order_by = '-score'

                    # get request data according to searched values
                    if category != 'Any Category':
                        last_page = Company.objects.filter(
                            query_set,
                            category__name=category).count()
                        objects = Company.objects.filter(
                            query_set,
                            category__name=category,
                        ).order_by(order_by)[first_slice:second_slice]
                    else:
                        last_page = Company.objects.filter(
                            query_set).count()
                        objects = Company.objects.filter(
                            query_set,
                        ).order_by(order_by)[first_slice:second_slice]
                print(len(objects))
            else:
                return HttpResponseRedirect('/error/400/')
        else:
            flag = True
            page_nr = request.GET.get('page', 1)
            try:
                page_nr = int(page_nr)
                if page_nr < 0:
                    raise Exception('Page number is negative')
            except Exception as exc:
                print('Exception: {}'.format(exc))
                return HttpResponseRedirect('/error/400/')
            first_slice = (page_nr-1) * 10
            second_slice = page_nr * 10
            order_by = 'name'
            last_page = Company.objects.all().count()
            objects = Company.objects.all().order_by(order_by)[first_slice:second_slice]
            copy_params = {
                'category': 'Any Category',
                'query': '',
                'submit': 1,
                'order': 'Alphabetic Ascending'
            }

        # append results in order to pass to template
        companies = []
        for comp in objects:
            if comp.image and comp.image != 'nophoto':
                try:
                    image = Image.open(BASE_DIR + '\\static\\img\\company\\'
                                       + '{:02d}'.format(comp.id)[-2:] + '\\{}.'.format(comp.id) + comp.image)
                except:
                    image = Image.open(BASE_DIR + '\\static\\images\\slider\\no_photo.png')
            else:
                image = Image.open(BASE_DIR + '\\static\\images\\slider\\no_photo.png')
            image_ratio = image.height / image.width
            if image_ratio > 170/140:
                style = 'height: 100%;'
            else:
                style = 'width: 100%;'

            description = comp.description.replace("''", "'")
            replaceable = re.search(r'</?div[^>]+>', description)
            while replaceable:
                description = description.replace(replaceable.group(0), '')
                replaceable = re.search(r'</?div[^>]+>', description)

            if comp.image and comp.image != 'nophoto':
                image_link = 'global/img/company/' + '{:02d}'.format(comp.id)[-2:] + '/{}.'.format(comp.id) + comp.image
            else:
                image_link = 'global/images/slider/no_photo.png'
            companies.append({
                'name': comp.name.replace("''", "'"),
                'style': style,
                'description' : description,
                'image_link': image_link,
                'comp_id': comp.id
            })
        search_form = SearchCompany(initial={'category': 'Any Category'})

        if page_nr <= 2:
            page_token_prev = 1
            page_token_1 = 1
            page_token_2 = 2
            page_token_3 = 3
            page_token_4 = 4
            page_token_5 = 5
            page_token_next = page_nr + 1
        else:
            page_token_prev = page_nr - 1
            page_token_1 = page_nr - 2
            page_token_2 = page_nr - 1
            page_token_3 = page_nr
            page_token_4 = page_nr + 1
            page_token_5 = page_nr + 2
            page_token_next = page_nr + 1
        if not flag:
            copy_params = {}
            for key in request.GET:
                if key != 'page':
                    copy_params[key] = request.GET[key]
        if last_page % 10 != 0:
            last_page = int(last_page / 10) + 1
        else:
            last_page = int(last_page / 10)
        context = {
            'companies': companies,
            'current_page': page_nr,
            'last_page': last_page,
            'page_token_1': page_token_1,
            'page_token_2': page_token_2,
            'page_token_3': page_token_3,
            'page_token_4': page_token_4,
            'page_token_5': page_token_5,
            'page_token_link_first': '/companies/search?' + urlencode(copy_params) + '&page=1',
            'page_token_link_prev': '/companies/search?' + urlencode(copy_params) + '&page={}'.format(page_token_prev),
            'page_token_link_1': '/companies/search?' + urlencode(copy_params) + '&page={}'.format(page_token_1),
            'page_token_link_2': '/companies/search?' + urlencode(copy_params) + '&page={}'.format(page_token_2),
            'page_token_link_3': '/companies/search?' + urlencode(copy_params) + '&page={}'.format(page_token_3),
            'page_token_link_4': '/companies/search?' + urlencode(copy_params) + '&page={}'.format(page_token_4),
            'page_token_link_5': '/companies/search?' + urlencode(copy_params) + '&page={}'.format(page_token_5),
            'page_token_link_next': '/companies/search?' + urlencode(copy_params) + '&page={}'.format(page_token_next),
            'page_token_link_last': '/companies/search?' + urlencode(copy_params) + '&page={}'.format(last_page),
            'search_form': search_form,
        }
        return render(request, 'company/search.html', context)

    # treat other types of requests on the search page
    return HttpResponseRedirect('/error/405/')


@login_required
def company_details(request, comp_id):
    try:
        comp = Company.objects.get(pk=int(comp_id))
    except ObjectDoesNotExist:
        return HttpResponseRedirect('/error/404/')
    if comp.image and comp.image != 'nophoto':
        try:

server/company/templates/company/base.html
{% extends "base.html" %}
{% block company_active %} class="active" {% endblock %}

server/company/templates/company/error.html
{% extends "company/base.html" %}
{% block  head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | EDEC</title>
    {% load staticfiles %}
    <!-- core CSS -->
    <link href="{% static 'global/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'global/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'global/css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'global/css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'global/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'global/css/responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
        <script src="{% static 'global/js/html5shiv.js' %}"></script>
        <script src="{% static 'global/js/respond.min.js' %}"></script>
        <![endif]-->
    <link rel="shortcut icon" href="{% static 'global/images/ico/favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
          href="{% static 'global/images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="{% static 'global/images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72"
          href="{% static 'global/images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed"
          href="{% static 'global/css/images/ico/apple-touch-icon-57-precomposed.png' %}">
{% endblock %}

{% block content %}
<section id="error" class="container text-center" style="padding-top: 200px;">
    <h1>{{ code }}, {{ message }}</h1>
    <p>{{ extended_message }}</p>
    <a class="btn btn-primary" href="index.html">BACK TO HOMEPAGE</a>
</section><!--/#error-->
{% block content %}

server/company/templates/company/search.html
{% extends "company/base.html" %}
{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Search Company | EDEC</title>

    {% load staticfiles %}

    <!-- core CSS -->
    <link href="{% static 'global/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'global/css/font-awesome.min.css' %}"
          rel="stylesheet">
    <link href="{% static 'global/css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'global/css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'global/css/productSearch.css' %}" rel="stylesheet">

    <link href="{% static 'global/css/responsive.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="{% static 'global/js/html5shiv.js' %}"></script>
    <script src="{% static 'global/js/respond.min.js' %}"></script>
    <![endif]-->
    <link rel="shortcut icon"
          href="{% static 'global/images/ico/favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144.4"
          href="{% static 'global/images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="{% static 'global/images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72"
          href="{% static 'global/images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed"
          href="{% static 'global/images/ico/apple-touch-icon-57-precomposed.png' %}">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
{% endblock %}
<!--/head-->

{% block content %}


<section id="services" class="service-item" style="padding-bottom: 160px;">
<div class="container">

<div class="media contact-info wow fadeInDown" data-wow-duration="1000ms"
     data-wow-delay="600ms">

<div class="media-body">

<div class="[ container text-center ]">
<div class="[ row ]">
<div class="[ col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 ]"
     role="tabpanel">

<div class="[ col-xs-8 col-sm-12 ]">

<!-- Tab panes -->

<!-- First pane -->

<form id="searchFormComp1">
                <h1 class="bold" style="margin-left: -40px; ">Search for Companies</h1>

                {{ search_form.category }}

                <div class="nav nav-justified navbar-nav">
                    <div class="input-group">
                        {{ search_form.query }}
                        <div class="input-group-btn">
                            <button type="submit"
                                    class="btn btn-search btn-danger"
                                    form="searchFormComp1" name="submit" value="1">
                                <span class="glyphicon glyphicon-search"></span>
                                <span class="label-icon">Search</span>
                            </button>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">

             

                        <!-- Subcategories -->

{#                        <h2 class="bold"#}
{#                            style="margin-left: 5px; padding-top: 20px;">Filter companies by their products' categories</h2>#}
{##}
{#                        <div style="padding-top: 10px;">#}
{#                            <h4 class="bold"#}
{#                                style="display: inline-block; color: white; padding-right: 10px;">#}
{#                                Category: </h4>#}
{##}
{#                            <div class="btn-group">#}
{#                                <button class="btn btn-danger" type="button"#}
{#                                        style="width: 360px;" id="menu1company">#}
{#                                    Any Category#}
{#                                </button>#}
{#                                <button data-toggle="dropdown"#}
{#                                        class="btn btn-danger dropdown-toggle"#}
{#                                        id="dropSubcategories1" type="button"#}
{#                                        name="change"><span#}
{#                                        class="caret"></span></button>#}
{#                                #}
{#                                #}
{#                                <ul class="dropdown-menu scrollable-menu"#}
{#                                    id="dropdown-company1" role="menu"#}
{#                                    style="height: auto; max-height: 150px; overflow-x: hidden; width: 100%;">#}
{#                                    <a>#}
{#                                        <li class="wrapTxt">Any Category<span#}
{#                                                    class="mask"></span></li>#}
{#                                    </a>#}
{#                                    #}
{#                                    <a>#}
{#                                        <li class="wrapTxt">Category 1<span#}
{#                                                class="mask"></span></li>#}
{#                                    </a>#}
{##}
{#                                    <a>#}
{#                                        <li class="wrapTxt">Category 2<span#}
{#                                                class="mask"></span></li>#}
{#                                    </a>#}
{##}
{#                                    <a>#}
{#                                        <li class="wrapTxt">Category 3<span#}
{#                                                class="mask"></span></li>#}
{#                                    </a>#}
{#                                    #}
{#                                </ul>#}
{#                            </div>#}
{#                        </div>#}

                        <div>

                              <h4 class="bold" style="display: inline-block; color: white;padding-right:20px; padding-top: 20px;">Order by: </h4>

                              <div class="btn-group">                            

                                <button class="btn btn-danger"  type="button" style="width:360px; " id="menu2company">Alphabetic Ascending</button>

                                <button data-toggle="dropdown" class="btn btn-danger dropdown-toggle" id="drop" type="button"><span class="caret"></span></button>

                                {{ search_form.order }}

                                <ul class="dropdown-menu" role="menu" style="height: auto; max-height: 180px; overflow-x: hidden; padding-left: 10px; width: 100%;" id="dropdown-company2">
                                  <a>
                                        <li class="wrapTxt">Alphabetic Ascending<span
                                                    class="mask"></span></li>
                                    </a>
                                    
                                    <a>
                                        <li class="wrapTxt">Alphabetic Descending<span
                                                class="mask"></span></li>
                                    </a>

                                    <a>
                                        <li class="wrapTxt">Relevance Ascending<span
                                                class="mask"></span></li>
                                    </a>

                                    <a>
                                        <li class="wrapTxt">Relevance Descending<span
                                                class="mask"></span></li>
                                    </a>
                                </ul>
                              </div>
                            </div>

                        <!-- Order for first tab -->

                    </div>
                </div>
            </form>
</section>
<!--/#services-->


<section id="blog" class="container">


    <div class="container wow fadeInDown" data-wow-duration="1000ms"
         data-wow-delay="600ms">

        <div class="row">

            <div class="col-md-12">
                <div class="container">
                    <table class="table table-striped">
                        <col width="400">
                        <col width="500">
                        <thead class="tables"
                               style="font-size: 25px; color: #ff8080;">
                        <tr>
                            <th>Company</th>
                            <th>Description</th>
                        </tr>
                        </thead>

                        <tbody>

                            {% for row in companies %}

                            <!-- Another company goes here -->

                            <tr class="selectableProduct clickable-row" data-href="/companies/details/{{ row.comp_id }}">
                                <td>
                                    <div style="float: left; height: 180px; margin-right: 15px; width: 140px; background: white;">
                                        <img src="{% static row.image_link %}" alt="Product Image - {{ row.name }}" style="{{ row.style }}">
                                    </div>
                                    <h4><b>{{ row.name }}</b></h4>
                                </td>

                                <td class="point prodDescription">
                                    <div class="cropDescription">
                                    {{ row.description | safe }}
                                    <div class="fadedDescription"></div>
                                    </div>
                                </td>
                            </tr>

                            {% endfor %}

                        </tbody>
                    </table>
                </div>

                <!-- Pagination -->

                <div class="text-center">
                <ul class="pagination pagination-lg">
                    <li><a href="{{ page_token_link_first }}"><i class="fa fa-angle-double-left"></i></a></li>
                    <li><a href="{{ page_token_link_prev }}"><i class="fa fa-angle-left"></i></a></li>
                    {% if page_token_1 <= last_page %}<li {%  if current_page == page_token_1 %}class="active"{% endif %}><a href="{{ page_token_link_1 }}">{{ page_token_1 }}</a></li>{% endif %}
                    {% if page_token_2 <= last_page %}<li {%  if current_page == page_token_2 %}class="active"{% endif %}><a href="{{ page_token_link_2 }}">{{ page_token_2 }}</a></li>{% endif %}
                    {% if page_token_3 <= last_page %}<li {%  if current_page == page_token_3 %}class="active"{% endif %}><a href="{{ page_token_link_3 }}">{{ page_token_3 }}</a></li>{% endif %}
                    {% if page_token_4 <= last_page %}<li {%  if current_page == page_token_4 %}class="active"{% endif %}><a href="{{ page_token_link_4 }}">{{ page_token_4 }}</a></li>{% endif %}
                    {% if page_token_5 <= last_page %}<li {%  if current_page == page_token_5 %}class="active"{% endif %}><a href="{{ page_token_link_5 }}">{{ page_token_5 }}</a></li>{% endif %}
                    <li><a href="{{ page_token_link_next }}"><i class="fa fa-angle-right"></i></a></li>
                    <li><a href="{{ page_token_link_last }}"><i class="fa fa-angle-double-right"></i></a></li>
                </ul>
                </div>

            </div>
        </div>
    </div>
</section>

<section id="partner">
    <div class="container">
        <div class="center wow fadeInDown">
            <h2>Top Companies</h2>
            <p class="lead">Descriere</p>
        </div>

        <div class="partners">
            <ul>
                <li>
                    <a href="{% url 'company:details' comp_id=428 %}"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms" src="{% static 'global/images/partners/cocacola.png' %}">
                    </a>
                </li>
                <li>
                    <a href="{% url 'company:details' comp_id=83 %}"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms" src="{% static 'global/images/partners/applelogo.png' %}">
                    </a>
                </li>
                <li>
                    <a href="{% url 'company:details' comp_id=1652 %}"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms" src="{% static 'global/images/partners/pringleslogo.png' %}">
                    </a>
                </li>
                <li>
                    <a href="{% url 'company:details' comp_id=1800 %}"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="1200ms" src="{% static 'global/images/partners/samsung.png' %}">
                    </a>
                </li>
                <li>
                    <a href="#"><img class="img-responsive wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="1500ms" src="{% static 'global/images/partners/nike.png' %}">
                    </a>
                </li>

                </ul>
            </div>
        </div>
        <!--/.container-->
    </section>
    <!--/#partner-->
{% endblock %}

{% block scripts %}
<script src="{% static 'global/js/jquery.js' %}"></script>
<script src="{% static 'global/js/bootstrap.min.js' %}"></script>
<script src="{% static 'global/js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'global/js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'global/js/main.js' %}"></script>
<script src="{% static 'global/js/wow.min.js' %}"></script>
{% endblock %}